import React from 'react'
export const metadata = {
  title: "Work-manager",
  description: "Generated by create next app",
};
const ShowTasks = () => {
  return (
    <div>
      <h2>show task</h2>
    </div>
  )
}

export default ShowTasks
