import React from 'react'
import ShowTasks from './Show-tasks';
export const metadata = {
  title: "Work-manager",
  description: "Generated by create next app",
};
const ShowTasksPage = () => {
  return <ShowTasks />;
};

export default ShowTasksPage
